name: ${project.name}
version: '${project.version}'
main: dev.mrfishcakes.prisoncore.PrisonCore
api-version: 1.17
authors: [ Fallen, MrFishCakes ]
description: Core plugin for prison
website: mrfishcakes.dev
